-- ============================================================================
-- STORAGE BUCKETS + RLS POLICIES
-- Run after 0001_init.sql. Buckets are also creatable via the Supabase
-- dashboard (Storage > New bucket) — this script does both for a clean
-- CLI-only setup (`supabase db push`).
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('event-images',   'event-images',   true,  5242880,  array['image/jpeg','image/png','image/webp']),
  ('gallery-photos',  'gallery-photos', false, 10485760, array['image/jpeg','image/png','image/webp']),
  ('avatars',         'avatars',        true,  2097152,  array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- event-images: public read (bucket is public), admin-only write
-- ---------------------------------------------------------------------------
create policy "event_images_public_read"
  on storage.objects for select
  using (bucket_id = 'event-images');

create policy "event_images_admin_write"
  on storage.objects for insert
  with check (bucket_id = 'event-images' and is_admin(auth.uid()));

create policy "event_images_admin_update"
  on storage.objects for update
  using (bucket_id = 'event-images' and is_admin(auth.uid()));

create policy "event_images_admin_delete"
  on storage.objects for delete
  using (bucket_id = 'event-images' and is_admin(auth.uid()));

-- ---------------------------------------------------------------------------
-- gallery-photos: private bucket. Upload path convention is
-- gallery-photos/{user_id}/{uuid}.webp — storage.foldername(name)[1] is the
-- first path segment, i.e. the uploader's own user id.
-- Public/approved-photo access goes through signed URLs generated by
-- Server Actions (RLS on the `photos` table already gates who can even
-- learn a photo's storage_path), not through a public storage policy.
-- ---------------------------------------------------------------------------
create policy "gallery_photos_owner_read"
  on storage.objects for select
  using (bucket_id = 'gallery-photos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "gallery_photos_admin_read"
  on storage.objects for select
  using (bucket_id = 'gallery-photos' and is_admin(auth.uid()));

create policy "gallery_photos_owner_upload"
  on storage.objects for insert
  with check (bucket_id = 'gallery-photos' and (storage.foldername(name))[1] = auth.uid()::text);

-- No owner update/delete policy — matches the spec: users cannot delete
-- their own approved photos. Only the service-role key (used inside the
-- deletePhoto Server Action, itself gated by requireAdmin()) can remove
-- gallery-photos objects.

-- ---------------------------------------------------------------------------
-- avatars: public read, owner can upload/replace their own
-- ---------------------------------------------------------------------------
create policy "avatars_public_read"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "avatars_owner_write"
  on storage.objects for insert
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "avatars_owner_update"
  on storage.objects for update
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
